version: "3.9"

networks:
  default:
    name: cybellum-network
    external: true

volumes:
  pg-data:
    name: cybellum_pg-data
    external: true

services:

  backend:
    restart: always
    container_name: cybellum-backend

    build: .

    volumes:
      - .:/app/

    ports:
      - "8000:8000"

    env_file:
      - .env

    command: gunicorn app.main:"create_flask_app()" -b 0.0.0.0:8000 --reload

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    container_name: cybellum-postgres

    image: postgres:alpine

    volumes:
      - pg-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d cybellum" ]
      interval: 1s
      timeout: 3s
      retries: 10

    env_file:
      - .env